// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCM_Y0Uwg7pxcfUjNO5EySaWFrCx_R6-jo',
    appId: '1:139054120092:web:5b3e2cf2a8251d72514159',
    messagingSenderId: '139054120092',
    projectId: 'corex-a1c1e',
    authDomain: 'corex-a1c1e.firebaseapp.com',
    databaseURL: 'https://corex-a1c1e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'corex-a1c1e.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCM_Y0Uwg7pxcfUjNO5EySaWFrCx_R6-jo',
    appId: '1:139054120092:web:5b3e2cf2a8251d72514159',
    messagingSenderId: '139054120092',
    projectId: 'corex-a1c1e',
    authDomain: 'corex-a1c1e.firebaseapp.com',
    databaseURL: 'https://corex-a1c1e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'corex-a1c1e.firebasestorage.app',
  );
}
